### ISSUE TITLE
Is LG name a good one?

### ISSUE THREAD

**Issue by pemensik** [joan2937/lg#6]
Is this project already packaged on Debian or another distribution? It seems lg is not the best name, because it conflicts with world-wide known company with LG logo. It might violate its trademark. I am preparing a package for Fedora, but I would expect this might stop a review.

Would it be possible to rename it to lgpio? Was there specific reason to name the repository this way?

**Comment by joan2937** [comment]
LG is not a good name.  It is called lg.
